foreground         #c3c6c9
background         #121c2a
background_opacity 1.0
cursor             #c3c6c9

active_tab_foreground     #121c2a
active_tab_background     #c3c6c9
inactive_tab_foreground   #c3c6c9
inactive_tab_background   #121c2a

active_border_color   #c3c6c9
inactive_border_color #121c2a
bell_border_color     #b1845a

color0       #121c2a
color8       #616a76
color1       #b1845a
color9       #ECB178
color2       #185268
color10      #206E8B
color3       #465466
color11      #5E7088
color4       #226f7d
color12      #2E94A7
color5       #437b84
color13      #5AA5B1
color6       #428d96
color14      #59BDC9
color7       #94989e
color15      #c3c6c9
