foreground         #c2c3c7
background         #0e1021
background_opacity 1.0
cursor             #c2c3c7

active_tab_foreground     #0e1021
active_tab_background     #c2c3c7
inactive_tab_foreground   #c2c3c7
inactive_tab_background   #0e1021

active_border_color   #c2c3c7
inactive_border_color #0e1021
bell_border_color     #454e5a

color0       #0e1021
color8       #5d5f72
color1       #454e5a
color9       #5D6878
color2       #60605d
color10      #81817C
color3       #505963
color11      #6B7785
color4       #5a6369
color12      #79858D
color5       #707574
color13      #969D9B
color6       #908f85
color14      #C0BFB2
color7       #91929b
color15      #c2c3c7
