source = /home/$USER/.cache/wal/colors-hyprland

general {
    background = $backgrouldCol
    text = $foregroundCol
    password_field_width = 340
    window_width         = 520
    window_height        = 440
    show_details         = true
}
